#! /usr/bin/awk -f 
{
sum=0;jack_bin=0;;c=NF-1;
avg=0;funt = 0;funt_sum = 0; 

for(i=2;i<=NF;i++) {
	sum+=$i;
}
avg = sum/c;

for(i=2;i<=NF;i++) { 
	jack_bin=(sum-$i)/(c-1);
	funt=(jack_bin-avg);
	funt_sum+=funt*funt;
}
printf"%f ", avg;
printf "%f\n", sqrt(((c-1)/c)*funt_sum);
}
