#! /bin/bash

#for i in {1..5}
#do 
#./energy > output_$i.dat
#done 

for i in {2..5}
do
	cut -d " " -f2 output_$i.dat > outputnew_$i.dat
done
paste -d " " output_1.dat outputnew_{2..5}.dat > energy.dat
exit 0
